version: '3'
services:
  web:
    build: .
    image: patchyvideo
    ports:
      - "5000:5000"
    depends_on:
      - db
      - redis
      - spider
    environment:
      - FLASK_ENV=production
      - REDISTOGO_URL_WORKER=redis://redis:6379
      - REDISTOGO_URL=redis
      - MONGODB_URL=mongodb://db:27017/patchyvideo
      - IMAGE_PATH=/var/www/images
      - ENABLE_TRANSACTION=true
  spider:
    image: patchyvideo
    command: python worker.py
    depends_on:
      - redis
    environments:
      - FLASK_ENV=production
      - REDISTOGO_URL_WORKER=redis://redis:6379
      - IMAGE_PATH=/var/www/images
      - MONGODB_URL=mongodb://db:27017/patchyvideo
      - REDISTOGO_URL=redis
      - ENABLE_TRANSACTION=true
  redis:
    image: redis
  db:
    image: mongo
    volumes:
      - './data:/data/db'